repos:
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort
      types: [python]
- repo: https://github.com/psf/black
  rev: 23.11.0
  hooks:
    - id: black
      name: black
      types: [python]
- repo: https://github.com/zricethezav/gitleaks
  rev: v8.18.1
  hooks:
    - id: gitleaks
