[tool.poetry]
name = "openassistants"
version = "0.0.1"
description = ""
authors = ["Rick Lamers <ricklamers@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.1.3"
fastapi = "^0.104.1"
starlette = ">=0.27.0,<0.28.0"
langchain = "^0.0.346"
jsonschema = "^4.20.0"
ruamel-yaml = "^0.18.5"
sqlalchemy = "^2.0.23"
openai = "^1.3.7"
duckdb-engine = "^0.9.3"

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
